name: Autobuild luci-app-oplist

on:
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check-upstream
        id: check_upstream
        run: |
          TAG=$(curl -s https://api.github.com/repos/OpenListTeam/OpenList/releases/latest | jq -r .tag_name)
          EXISTS=$(curl -s https://api.github.com/repos/mokanove/luci-app-oplist/releases/tags/$TAG | jq -r .tag_name)

          if [ "$TAG" == "$EXISTS" ]; then
            echo "status=skip" >> $GITHUB_OUTPUT
            echo "There is nothing to do."
            exit 1
          else
            echo "status=go" >> $GITHUB_OUTPUT
            echo "tag=$TAG" >> $GITHUB_OUTPUT
          fi

      - name: install env
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses5-dev libncursesw5-dev \
            zlib1g-dev gawk git gettext libssl-dev xsltproc rsync wget unzip zstd

      - name: download source code
        run: |
          curl -LO https://immortalwrt.kyarucloud.moe/releases/24.10.4/targets/x86/64/immortalwrt-sdk-24.10.4-x86-64_gcc-13.3.0_musl.Linux-x86_64.tar.zst
          tar -xvf immortalwrt-sdk-24.10.4-x86-64_gcc-13.3.0_musl.Linux-x86_64.tar.zst
          cd immortalwrt-sdk-24.10.4-x86-64_gcc-13.3.0_musl.Linux-x86_64/package/
          git clone https://github.com/mokanove/luci-app-oplist.git

      - name: download latest openlist
        run: |
          cd immortalwrt-sdk-24.10.4-x86-64_gcc-13.3.0_musl.Linux-x86_64/package/luci-app-oplist/root/usr/bin
          DL_URL=$(curl -s https://api.github.com/repos/OpenListTeam/OpenList/releases/latest | jq -r '.assets[] | select(.name | contains("musl-amd64.tar.gz")) | .browser_download_url')
          curl -LO ${DL_URL}
          tar -xzvf *.tar.gz
          chmod +x openlist
          rm -f *.tar.gz DONOTREMOVE

      - name: make
        run: |
          cd immortalwrt-sdk-24.10.4-x86-64_gcc-13.3.0_musl.Linux-x86_64
          rm -f package/luci-app-oplist/root/etc/openlist/DONOTREMOVE
          cd package/luci-app-oplist
          NEW_RELEASE=$(date +%s)
          sed -i "s/PKG_RELEASE:=.*/PKG_RELEASE:=${NEW_RELEASE}/g" ./Makefile
          echo "Makefile updated, PKG_RELEASE now is : ${NEW_RELEASE}"
          cd ../../
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          make defconfig
          make package/luci-app-oplist/compile V=s -j$(nproc)

      - name: find-ipk
        run: |
          mkdir -p output
          find immortalwrt-sdk-24.10.4-x86-64_gcc-13.3.0_musl.Linux-x86_64/bin/packages/x86_64/ -name "*.ipk" -exec cp {} output/ \;

      - name: Release
        uses: softprops/action-gh-release@v1
        if: success()
        with:
          tag_name: ${{ steps.check_upstream.outputs.tag }}
          files: output/*.ipk
          body: |
            - OpenList Updated to : ${{ steps.check_upstream.outputs.tag }}
            - There is an auto release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
